jwt:
  secret: ${JWT_SECRET}
  zone: America/Guatemala
  access-token:
    expiration: 5
  refresh-token:
    expiration: 10_080

server:
  port: 8000
spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: ${VM_IP:http://localhost:4200}
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "*"
            maxAge: 3600
      routes:
        - id: user-public-routes
          uri: ${USER_ROUTE_URI:http://localhost:8001}
          predicates:
            - Path=/v1/users/authenticate,/v1/tokens/**
        - id: company-public-routes
          uri: ${USER_ROUTE_URI:http://localhost:8003}
          predicates:
            - Path=/v1/settings/**
        - id: company-private-routes
          uri: ${USER_ROUTE_URI:http://localhost:8003}
          predicates:
            - Path=/v1/pages/**
          filters:
            - JWTVerifyFilterFactory
        - id: project-private-routes
          uri: ${USER_ROUTE_URI:http://localhost:8002}
          predicates:
            - Path=/v1/projects/**,/v1/cases/**,/v1/type_cases/**,/v1/comments/**,/v1/history/**
          filters:
            - JWTVerifyFilterFactory
        - id: user-private-routes
          uri: ${USER_ROUTE_URI:http://localhost:8001}
          predicates:
            - Path=/v1/users/**,/v1/roles/**
          filters:
            - JWTVerifyFilterFactory
