ALTER TABLE users ADD COLUMN token TEXT;
ALTER TABLE users ADD COLUMN first_name VARCHAR(100) NOT NULL;
ALTER TABLE users ADD COLUMN last_name VARCHAR(100) NOT NULL;
ALTER TABLE users ADD COLUMN password TEXT NOT NULL;