
server:
  port: 8003
spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  application:
    name: ms_company
  datasource:
    url: ${DB_URL_COMPANY}
    username: ${DB_USERNAME_COMPANY}
    password: ${DB_PASSWORD_COMPANY}
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
      idle-timeout: 60000
      max-lifetime: 1800000
      connection-timeout: 30000
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MariaDBDialect