CREATE TABLE modules(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL UNIQUE,
    FK_Role INT NOT NULL,
    path VARCHAR(100) NOT NULL,
    is_enabled BOOLEAN DEFAULT TRUE
);