CREATE TABLE pages(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL UNIQUE,
    path VARCHAR(100) NOT NULL,
    FK_Module INT NOT NULL,
    is_enabled BOOLEAN DEFAULT TRUE
);